baseURL = 'https://opalbolt.github.io/blog/'
languageCode = 'en-us'
title = 'OpalBolt'
theme = 'default'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[security]
  enableInlineShortcodes = true

